version: 0.1

phases:
  install:
    commands:
      - gem install bundler
      - curl -sL  https://deb.nodesource.com/setup_14.x
      - apt-get update 
      - apt-get install nodejs -y
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
      - aws s3 sync --delete _site/ s3://doc.tuertolin.com
      - aws cloudfront create-invalidation --distribution-id E2V5UBJ2BX66LN --paths '/*'
